apiVersion: data.packaging.carvel.dev/v1alpha1
kind: PackageMetadata
metadata:
  creationTimestamp: null
  name: argocd-attach.fling.vsphere.vmware.com
spec:
  displayName: ArgoCD Attach Service
  longDescription: Provides the ability to auto attach clusters to ArgoCD
  shortDescription: ArgoCD Auto Attach

---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  creationTimestamp: null
  name: argocd-attach.fling.vsphere.vmware.com.3.0.6
spec:
  refName: argocd-attach.fling.vsphere.vmware.com
  releasedAt: "2026-02-19T15:47:16Z"
  template:
    spec:
      deploy:
      - kapp: {}
      fetch:
      - imgpkgBundle:
          image: ghcr.io/warroyo/argocd-attach-service@sha256:742381de82c7732dfaf9f03dcc5dab3c4736a692830b53df8f1f9086fcf937ef
      template:
      - ytt:
          paths:
          - config
      - kbld:
          paths:
          - '-'
          - .imgpkg/images.yml
  valuesSchema:
    openAPIv3:
      additionalProperties: false
      properties:
        blocked_namespaces:
          default: []
          items:
            default: ""
            type: string
          type: array
        namespace:
          default: ""
          type: string
        resync_period:
          default: "60"
          type: string
      type: object
  version: 3.0.6
